### ISSUE TITLE
Payment received history shows wrong amount with 0 invoices

### ISSUE THREAD

**Issue by odniklas** [LN-Zap/zap-iOS#71] opened 2019-01-04 08:41 UTC
**Describe the bug**
Payment received history shows the wrong amount if an invoice with 0 amount is created and is payed with an amount larger than 0

**To Reproduce**
1. Create an invoice with 0 sat 
2. Pay the invoice from another account with 10 sat
3. The invoice shows up as payed 0 sat

**Expected behavior**
Invoice should show 10 sat payed even if the requested amount was 0. Everything else in the UI reflects that the payment has been made with the correct amount.

**Your environment**
- iPhone X

```
 {
            "memo": "",
            "receipt": null,
            "r_preimage": "",
            "r_hash": "",
            "value": "0",  <---- dont use this value
            "settled": true,
            "creation_date": "1546588826",
            "settle_date": "1546588867",
            "payment_request": "",
            "description_hash": null,
            "expiry": "3600",
            "fallback_addr": "",
            "cltv_expiry": "144",
            "route_hints": [
            ],
            "private": false,
            "add_index": "5",
            "settle_index": "1",
            "amt_paid": "43485000",  <--- use this value instead
            "amt_paid_sat": "43485",
            "amt_paid_msat": "43485000"
        }
```

**Comment by ottosuess** [comment] 2019-01-14 13:59
i just tested this and for me it shows the correct amounts. both when paying and receiving to 0 amount invoices. 🤔

you can see the 0 amount request, and the 5 sat payment.
![screenshot 2019-01-14 at 12 55 18](https://user-images.githubusercontent.com/37940680/51111224-abea4d00-17fb-11e9-9b51-7152eddb7b49.png)

**Comment by AmazingDroopy** [comment] 2019-02-28 23:00
I have a similar issue with a 0 SAT invoice, which is not expired. Meanwhile I create 2 invoices that are shown in the history, but the payments that are succesfullt made do not, while the LND Remote client log shows the payment as expected.

**Comment by ottosuess** [comment] 2019-03-01 08:50
i think i fixed that issue, but haven't released the new alpha yet. Should be coming soon!
Please let me know if the new version fixes the issue for you. 😻

**Comment by AmazingDroopy** [comment] 2019-03-01 22:26
Great work. 
I just upgraded and the history shows the received payments.

I will repeat the process that led to the situation to see if it returns or not.


Richard.

**Comment by AmazingDroopy** [comment] 2019-03-01 22:45
Looks like you nailed it.

Repeated the issue causing process and this time all worked as expected.

0 SAT invoice
Sent 1000 SAT
Invoice for 2000 SAT
Receive 2000 SAT

....However, is it by design that PAYED invoices keep counting down the whole validity period to expire?

I would expect, these invoices would change to settled.

Richard.

**Comment by ottosuess** [comment] 2019-03-04 17:24
good find, i'll close this and create an other issue for the count down bug.

**Closed by ottosuess** 2019-03-04 17:24 UTC
Labels: bug
